# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\showClass.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_classShowing(QtWidgets.QWidget):
    def __init__(self):
        super(self).__init__()
        self.setupUi(self)
    def setupUi(self, classShowing):
        classShowing.setObjectName("classShowing")
        classShowing.resize(420, 320)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        classShowing.setFont(font)
        classShowing.setWindowOpacity(0.8)
        self.widget = QtWidgets.QWidget(classShowing)
        self.widget.setGeometry(QtCore.QRect(10, 10, 400, 300))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.widget.setFont(font)
        self.widget.setStyleSheet(".QWidget{border-radius: 10px;background-color: rgb(255, 245, 238);border: 2px solid blue;}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 380, 280))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(classShowing)
        QtCore.QMetaObject.connectSlotsByName(classShowing)

    def retranslateUi(self, classShowing):
        _translate = QtCore.QCoreApplication.translate
        classShowing.setWindowTitle(_translate("classShowing", "Form"))
        self.label.setText(_translate("classShowing", "<html><head/><body><p align=\"center\"><span style=\" font-size:30pt;\">上节课: </span><span style=\" font-size:40pt; font-weight:600; color:#ff0000;\">语文</span></p><p align=\"center\"><span style=\" font-size:30pt;\">下节课: </span><span style=\" font-size:40pt; font-weight:600; color:#0000ff;\">数学</span></p><p align=\"center\"><span style=\" font-size:22pt; color:#000000;\">22/11/5 12:20:02</span></p></body></html>"))
